version: '3.8'

services:
  backend:
    build: .
    container_name: vkart-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: on-failure
    networks:
      - vkart-network

networks:
  vkart-network:
    driver: bridge